program PRINCONJUNTO;
USES uconjunto;


var
A,B,R:conjunto;

begin
   CREARCONJUNTO(A);
   CREARCONJUNTO(b);


   INSERTAR(A,5);
   INSERTAR(A,7);
   INSERTAR(A,9);

   WRITELN('CONJUNTO A: ');
   MOSTRARCONJUNTO(A);


   
   INSERTAR(B,1);
   INSERTAR(B,5);
   INSERTAR(B,7);
   INSERTAR(B,8);

   WRITELN('CONJUNTO B: ');
   MOSTRARCONJUNTO(B);


   R:= INTERSECCION(A,B);
   WRITELN('INTERSECCION DE A y B: ');
   MOSTRARCONJUNTO(R);

   CREARCONJUNTO(R);
   R:=UNION(A,B);
   WRITELN('UNION DE A Y B : ');
   MOSTRARCONJUNTO(R);

   CREARCONJUNTO(R);
   R:=DIFERENCIA(A,B);
   WRITELN('DIFERENCIA DE A - B : ');
   MOSTRARCONJUNTO(R);


READLN;

end.
